import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/navbar/navbar";
import 'aos/dist/aos.css'
import { Aos } from "@/components/aos";
import { QueryProvider } from "@/lib/tanstackquery";
import { SlideBar } from "@/components/slidebar/slideBar";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Social Network",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Aos />
      <body className={inter.className}>
        <div className='flex md:flex-row flex-col justify-between min-h-[100vh] p-0 '>
          <SlideBar />
          <div className="flex-[4]">
            {children}
          </div>
          <Navbar />
        </div>
      </body>
    </html>
  );
}
